context: {}

package:
  name: cellphonedb
  version: 5.0.1

source:
- url: https://files.pythonhosted.org/packages/74/c2/195d1bd3023ff0e0a11997ac580e258f0af0d0ef01de9f9c6358654e5597/cellphonedb-5.0.1.tar.gz
  sha256: 8c041831e184a28be5dea039c3e0dbd24bb7f4c1e56d62605f3c7542355ef96e

build:
  noarch: python
  script: python -m pip install .

requirements:
  host:
  - poetry-core >=1.0.0
  - python >=3.8, <4.0
  - pip
  run:
  - python >=3.8, <4.0
  - anndata >=0.8
  # - black >=22.3  # extra == 'dev'
  - geosketch >=1.2
  # - isort >=5.7  # extra == 'dev'
  - ktplotspy >=0.1.4
  - numpy >=1.21.6
  - numpy_groupies >=0.9.15
  - pandas >=1.5.0
  - pytest >=7.2.0
  - requests >=2.25.0
  - scanpy >=1.9.1
  - scikit-learn >=1.2.2
  - tqdm >=4.3, <5.0

tests: []

about:
  homepage: https://github.com/ventolab/cellphonedb
  summary: Inferring cell-cell communication.
  license: MIT


