context: {}

package:
  name: r-unigd
  version: 0.1.3

source:
- url: https://cran.r-project.org/src/contrib/unigd_0.1.3.tar.gz
  sha256: 27f3315ef93848f72653662e14d2c95d69da5c44d5424b56f64a66149d96d347

build:
  script: R CMD INSTALL --build .

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - make
  - pkg-config
  - autoconf
  host:
  - r-base >=3.2.0
  - r-cpp11 >=0.2.4
  - r-systemfonts >=1.0.0
  - cairo
  - libpng
  - libtiff
  - expat
  - zlib
  run:
  - r-base
  - r-systemfonts >=1.0.0
  - r-cpp11 >=0.2.4

tests:
- script:
  - Rscript -e 'library("unigd")'

about:
  homepage: https://github.com/nx10/unigd
  summary: Universal Graphics Device
  description: |-
    A unified R graphics backend. Render R graphics fast and
    easy to many common file formats. Provides a thread safe 'C'
    interface for asynchronous rendering of R graphics.
  license: GPL-2.0-or-later
  repository: https://github.com/cran/unigd

