package:
  name: r-unigd
  version: 0.1.3

source:
  url: https://cran.r-project.org/src/contrib/unigd_0.1.3.tar.gz
  sha256: 1df76ab42fa3ab4cbf1c8e27aabeb352e939a5b861f6853987e8b8daf73b0ab3

build:
  string: ${{ "r" + r_base|replace(".", "") }}h${{ hash }}
  script: R CMD INSTALL --build .
  variant:
    use_keys:
      - r_base
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - pkg-config
    - autoconf
  host:
    - r-base
    - r-cpp11 >=0.2.4
    - r-systemfonts >=1.0.0
    - xorg-xproto
    - xorg-kbproto
    - xorg-xextproto
    - xorg-renderproto
    - cairo
    - freetype
    - libtiff
    - expat
    - libpng
    - zlib
    - fontconfig
  run:
    - r-base = ${{r_base}}
    - r-cpp11 >=0.2.4
    - r-systemfonts >=1.0.0

tests:
  - script:
      - Rscript -e 'library("unigd")'

about:
  homepage: https://github.com/nx10/unigd
  summary: Universal Graphics Device
  description: |
    A unified R graphics backend. Render R graphics fast and
    easy to many common file formats. Provides a thread safe 'C'
    interface for asynchronous rendering of R graphics.
  license: GPL-2.0-or-later
  repository: https://github.com/cran/unigd
