context: {}

package:
  name: ktplotspy
  version: 0.2.4

source:
- url: https://files.pythonhosted.org/packages/cb/0c/42d2e8c0818dadc2519f574a69c10b55dd5bbad22a515e2343ac4a6ad865/ktplotspy-0.2.4.tar.gz
  sha256: 07ccf2eb7191391c52a7e054160e7544ea57ff2a6a3fc5c016269ca7e3b60403

build:
  noarch: python
  script: python -m pip install .

requirements:
  host:
  - poetry-core >=1.0.0
  - python >=3.8, <4.0
  - pip
  run:
  - python >=3.8, <4.0
  # - anndata >=0.7.6, <0.10.0  # extra == 'test'
  # - black  # extra == 'test'
  # - nbsphinx <=0.9.4  # extra == 'docs'
  - numpy >=1.23.5, <2.0.0
  - pandas >=1.5, <3.0
  - plotnine >=0.12.0, <0.13.0
  # - pytest-cov  # extra == 'test'
  - python-circos >=0.3.0, <0.4.0
  # - readthedocs-sphinx-ext <=2.2.5  # extra == 'docs'
  # - recommonmark <=0.7.1  # extra == 'docs'
  - requests >=2.28.0, <3.0.0
  - seaborn >=0.12, <0.14
  # - sphinx <7  # extra == 'docs'
  # - sphinx-autodoc-typehints <=1.23.0  # extra == 'docs'
  # - sphinx_rtd_theme <=2.0.0  # extra == 'docs'

tests: []

about:
  homepage: https://github.com/zktuong/ktplotspy
  summary: Python library for plotting Cellphonedb results. Ported from ktplots R package.
  license: MIT


